- id: doi:10.1101/2024.09.16.613355
  type: paper
  description: Prediction and functional interpretation of inter-chromosomal genome architecture from DNA sequence with TwinC.
  date: 2025-07-11
  image: https://www.biorxiv.org/content/10.1101/2024.09.16.613355v3
  buttons:
    - type: GitHub
      link: https://github.com/Noble-Lab/twinc
  tags:
    - 3D Genome
    - Trans-contacts
  repo: https://github.com/Noble-Lab/twinc

- id: doi:10.1093/nar/gkae1260
  image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/94e3/11797022/5413fe56e7da/gkae1260figgra1.jpg

- id: doi:10.1101/2025.01.20.633986.
  image: https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=276129&s=207&r=3&c=1

- id: doi:10.1101/2025.01.20.633986.
  image: https://www.ncbi.nlm.nih.gov/corecgi/tileshop/tileshop.fcgi?p=PMC3&id=276129&s=207&r=3&c=1
  
- id: doi: 10.1101/2024.12.16.628821
  image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/01d0/11702576/63c7a47cb428/nihpp-2024.12.16.628821v1-f0001.jpg

- id: doi:10.1101/gr.279095.124
  image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/406f/11610455/15fb8b2e56e3/1976f01.jpg

- id: doi:10.1093/bioinformatics/btae211
  image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/82c4/11211821/50520d60d8fc/btae211f1.jpg 

- id: doi:10.1186/s13059-022-02681-3.
  image: https://cdn.ncbi.nlm.nih.gov/pmc/blobs/b04d/9112525/0b1530676524/13059_2022_2681_Fig6_HTML.jpg

